import type { TurnstileVerifyResult } from "./create-vendor-inquiry.ts";

/**
 * Calls Cloudflare's Turnstile siteverify endpoint to confirm a token
 * generated by the widget in the browser is genuine and unused.
 *
 * Where its data comes from: the `token` the frontend sent us (originally
 * produced by the Turnstile widget), plus TURNSTILE_SECRET_KEY, which is
 * a Supabase Edge Function secret (set via `supabase secrets set`) — never
 * exposed to the browser, since anyone holding it could fabricate
 * "successful" verifications.
 *
 * Where its output goes: back to createVendorInquiry, which uses
 * `.success` to decide whether to proceed with the database insert.
 *
 * Kept as a standalone function (not inlined in create-vendor-inquiry.ts)
 * so it can be dependency-injected in tests — the test file mocks this
 * entire function rather than mocking `fetch`, which keeps tests from
 * being coupled to Cloudflare's exact response shape.
 */
export async function verifyTurnstile(
  token: string,
  secretKey: string,
): Promise<TurnstileVerifyResult> {
  const response = await fetch(
    "https://challenges.cloudflare.com/turnstile/v0/siteverify",
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ secret: secretKey, response: token }),
    },
  );

  if (!response.ok) {
    throw new Error(`Turnstile siteverify responded with ${response.status}`);
  }

  const result = (await response.json()) as {
    success: boolean;
    "error-codes"?: string[];
  };

  return {
    success: result.success,
    errorCodes: result["error-codes"],
  };
}