import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";
import { tanstackRouter } from "@tanstack/router-plugin/vite";
import path from "node:path";
import { configDefaults, coverageConfigDefaults } from "vitest/config";

// We import defineConfig from "vitest/config" instead of plain "vite" —
// it's the same function, but its TypeScript type is Vite's UserConfig
// extended with the `test` key (see the `test` block below). Importing
// from "vite" directly would make TypeScript reject `test` as an unknown
// property, since Vite itself has no concept of Vitest's config.
//
// Vite's config file. This controls how the dev server runs, how the
// production build is bundled, AND (via the `test` block below) how
// Vitest runs — Vitest reuses this same config so you don't maintain
// two separate setups for "run the app" vs "run the tests".
export default defineConfig({
  // The React plugin gives us JSX support and Fast Refresh (instant
  // in-browser updates when you save a file, without losing component state).
  plugins: [
    tanstackRouter({ target: "react", autoCodeSplitting: true }),
    react(),
  ],

  resolve: {
    alias: {
      // Mirrors the "@/*" path alias declared in tsconfig.app.json.
      // Both need to point at the same place — TypeScript uses its copy
      // for type-checking in your editor, Vite uses this copy to actually
      // resolve the import at build/dev time.
      //
      // import.meta.dirname (not __dirname) because this file runs as
      // native ESM — package.json has "type": "module", and __dirname is
      // a CommonJS-only global that simply doesn't exist in ESM scope.
      // import.meta.dirname is Node's built-in ESM equivalent, available
      // since Node 20.11 (we're on Node 24, well past that floor).
      "@": path.resolve(import.meta.dirname, "./src"),
    },
  },

  test: {
    // Scope Vitest to look inside src/ AND the Edge Functions logic
    // modules under supabase/functions/. Still excludes anything importing
    // from @playwright/test (e2e/*.spec.ts) — that pattern doesn't match
    // either glob below, so Playwright and Vitest stay in their own lanes
    // as before.
    include: [
      "src/**/*.{test,spec}.{ts,tsx}",
      "supabase/functions/**/*.{test,spec}.ts",
      "scripts/**/*.{test,spec}.ts",
    ],

    // jsdom simulates a browser DOM inside Node, which is what lets
    // React Testing Library render components and query them in tests
    // without an actual browser window.
    environment: "jsdom",

    // Runs before every test file — see src/test/setup.ts. This is where
    // we extend Vitest's `expect` with jest-dom matchers like
    // `.toBeInTheDocument()`.
    setupFiles: "./src/test/setup.ts",

    // Lets you write `describe`, `it`, `expect` without importing them
    // in every single test file.
    globals: true,

    exclude: [...configDefaults.exclude, 
      "**/*.integration.test.ts"],

    coverage: {
      provider: "v8",
      reporter: ["text", "html"],
      // Coverage is scoped separately from test.include above: this
      // controls which files Vitest reports coverage FOR (and measures
      // against the threshold below), not which files contain tests.
      //
      // include: real application source only. Left unset entirely
      // (as it was before GLPDX-84), v8's coverage.all mode tries to
      // report coverage for every file it can find project-wide --
      // including scripts/admin/*, which broke CI by trying to import
      // those files as if they were test suites.
      include: ["src/**", "supabase/functions/**"],

      // exclude: carves out categories of files that were being swept
      // into the include globs above but were never meant to count
      // toward the coverage bar -- either because they're not
      // executable business logic, or because attempting to parse them
      // for coverage produces noise/errors without adding signal.
      exclude: [
        ...coverageConfigDefaults.exclude,
        "scripts/**",
        // Test infrastructure (helpers, setup files) is not app code --
        // grading it against the same threshold as product logic
        // doesn't make sense.
        "src/test/integration/**",
        // Type-only declaration files have no runtime behavior to cover.
        "**/*.d.ts",
        // CSS Modules always report 0% under the v8 provider -- this is
        // a known false negative of the tool, not missing test coverage.
        "**/*.css",
        // Auto-generated by TanStack Router -- never hand-edited or
        // meant to be directly tested.
        "**/routeTree.gen.ts",
        // Documentation, not code.
        "**/*.md",
        // Env files were being picked up by the supabase/functions/**
        // glob and causing (harmless but noisy) parse-error warnings.
        "**/.env*",
        // Edge Function entry points (index.ts) are deliberately kept
        // minimal by design -- see the WHAT THIS FILE DOES comment in
        // handle-vendor-invite/index.ts: business logic is extracted
        // into separate modules specifically so it CAN be unit tested,
        // since Deno's runtime can't run this project's Node-based
        // Vitest suite directly against the entry point itself.
        "supabase/functions/*/index.ts",
        // src/main.tsx: the app's real bootstrap (createRoot, the real
        // generated routeTree.gen.ts, real Supabase-backed hooks pulled
        // in transitively). Repeated attempts (GLPDX-169) to render or
        // import it in the test environment hit TanStack Router
        // internals -- duplicate route registration against state the
        // router plugin owns globally -- that aren't practically
        // testable in isolation without a full browser-equivalent
        // environment. main.tsx itself has no independent branching
        // logic of its own to test; excluded as an accepted, documented
        // gap rather than a silent one.
        "src/main.tsx",
      ],
      thresholds: {
        lines: 80,
        functions: 80,
        branches: 75,
        statements: 80,
      },
    },
  },
});